# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 803)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Main_Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Main_Tab.setGeometry(QtCore.QRect(0, 0, 1441, 821))
        self.Main_Tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Main_Tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.Main_Tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Main_Tab.setObjectName("Main_Tab")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Data_Table = QtWidgets.QTableWidget(self.tab_2)
        self.Data_Table.setGeometry(QtCore.QRect(0, 50, 1431, 701))
        self.Data_Table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Data_Table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Data_Table.setAlternatingRowColors(True)
        self.Data_Table.setObjectName("Data_Table")
        self.Data_Table.setColumnCount(3)
        self.Data_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Data_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Data_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Data_Table.setHorizontalHeaderItem(2, item)
        self.Data_Table.horizontalHeader().setDefaultSectionSize(200)
        self.Data_Table.horizontalHeader().setStretchLastSection(True)
        self.Data_Import_Button = QtWidgets.QPushButton(self.tab_2)
        self.Data_Import_Button.setGeometry(QtCore.QRect(20, 10, 113, 32))
        self.Data_Import_Button.setObjectName("Data_Import_Button")
        self.Delete_Data_Button = QtWidgets.QPushButton(self.tab_2)
        self.Delete_Data_Button.setGeometry(QtCore.QRect(150, 10, 113, 32))
        self.Delete_Data_Button.setObjectName("Delete_Data_Button")
        self.Main_Tab.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 471, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Label_Ant_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Label_Ant_Layout.setContentsMargins(0, 0, 0, 0)
        self.Label_Ant_Layout.setObjectName("Label_Ant_Layout")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(480, 0, 471, 401))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.Label_Individual_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.Label_Individual_Layout.setContentsMargins(0, 0, 0, 0)
        self.Label_Individual_Layout.setObjectName("Label_Individual_Layout")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(960, 0, 471, 401))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.Label_Population_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.Label_Population_Layout.setContentsMargins(0, 0, 0, 0)
        self.Label_Population_Layout.setObjectName("Label_Population_Layout")
        self.Label_HSlider = QtWidgets.QSlider(self.tab)
        self.Label_HSlider.setGeometry(QtCore.QRect(70, 453, 1101, 22))
        self.Label_HSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Label_HSlider.setObjectName("Label_HSlider")
        self.Label_Play_Button = QtWidgets.QPushButton(self.tab)
        self.Label_Play_Button.setGeometry(QtCore.QRect(0, 450, 71, 32))
        self.Label_Play_Button.setObjectName("Label_Play_Button")
        self.Label_Frame_Number_Label = QtWidgets.QLabel(self.tab)
        self.Label_Frame_Number_Label.setGeometry(QtCore.QRect(1290, 448, 81, 29))
        self.Label_Frame_Number_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Frame_Number_Label.setWordWrap(True)
        self.Label_Frame_Number_Label.setObjectName("Label_Frame_Number_Label")
        self.Label_Left_Button = QtWidgets.QPushButton(self.tab)
        self.Label_Left_Button.setGeometry(QtCore.QRect(1240, 448, 51, 30))
        self.Label_Left_Button.setObjectName("Label_Left_Button")
        self.Label_Right_Button = QtWidgets.QPushButton(self.tab)
        self.Label_Right_Button.setGeometry(QtCore.QRect(1380, 448, 51, 30))
        self.Label_Right_Button.setObjectName("Label_Right_Button")
        self.Label_Population_ComboBox = QtWidgets.QComboBox(self.tab)
        self.Label_Population_ComboBox.setGeometry(QtCore.QRect(1223, 407, 211, 26))
        self.Label_Population_ComboBox.setObjectName("Label_Population_ComboBox")
        self.Label_Population_ComboBox.addItem("")
        self.Label_Population_ComboBox.addItem("")
        self.Label_Individual_ComboBox = QtWidgets.QComboBox(self.tab)
        self.Label_Individual_ComboBox.setGeometry(QtCore.QRect(740, 407, 211, 26))
        self.Label_Individual_ComboBox.setObjectName("Label_Individual_ComboBox")
        self.Label_Individual_ComboBox.addItem("")
        self.Label_Ant_ComboBox = QtWidgets.QComboBox(self.tab)
        self.Label_Ant_ComboBox.setGeometry(QtCore.QRect(260, 406, 211, 26))
        self.Label_Ant_ComboBox.setObjectName("Label_Ant_ComboBox")
        self.Label_Ant_ComboBox.addItem("")
        self.Label_Ant_ComboBox.addItem("")
        self.Label_Ant_ComboBox.addItem("")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(0, 430, 1431, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Label_Behavior_Label = QtWidgets.QLabel(self.tab)
        self.Label_Behavior_Label.setGeometry(QtCore.QRect(30, 620, 60, 16))
        self.Label_Behavior_Label.setObjectName("Label_Behavior_Label")
        self.Label_Add_Behavior_LineEdit = QtWidgets.QLineEdit(self.tab)
        self.Label_Add_Behavior_LineEdit.setGeometry(QtCore.QRect(100, 620, 171, 21))
        self.Label_Add_Behavior_LineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Label_Add_Behavior_LineEdit.setObjectName("Label_Add_Behavior_LineEdit")
        self.Label_Add_Button = QtWidgets.QPushButton(self.tab)
        self.Label_Add_Button.setGeometry(QtCore.QRect(280, 617, 101, 32))
        self.Label_Add_Button.setObjectName("Label_Add_Button")
        self.Label_Behavior_Label_2 = QtWidgets.QLabel(self.tab)
        self.Label_Behavior_Label_2.setGeometry(QtCore.QRect(400, 620, 61, 16))
        self.Label_Behavior_Label_2.setObjectName("Label_Behavior_Label_2")
        self.Label_Behavior_ComboBox = QtWidgets.QComboBox(self.tab)
        self.Label_Behavior_ComboBox.setGeometry(QtCore.QRect(488, 617, 210, 26))
        self.Label_Behavior_ComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Label_Behavior_ComboBox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.Label_Behavior_ComboBox.setObjectName("Label_Behavior_ComboBox")
        self.Label_Enter_Button = QtWidgets.QPushButton(self.tab)
        self.Label_Enter_Button.setGeometry(QtCore.QRect(850, 700, 91, 32))
        self.Label_Enter_Button.setObjectName("Label_Enter_Button")
        self.dashLabel = QtWidgets.QLabel(self.tab)
        self.dashLabel.setGeometry(QtCore.QRect(600, 650, 16, 16))
        self.dashLabel.setObjectName("dashLabel")
        self.Label_Frame_Range_Label = QtWidgets.QLabel(self.tab)
        self.Label_Frame_Range_Label.setGeometry(QtCore.QRect(400, 650, 91, 20))
        self.Label_Frame_Range_Label.setObjectName("Label_Frame_Range_Label")
        self.Label_Comment_Label = QtWidgets.QLabel(self.tab)
        self.Label_Comment_Label.setGeometry(QtCore.QRect(400, 690, 61, 20))
        self.Label_Comment_Label.setObjectName("Label_Comment_Label")
        self.Label_Comment_TextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.Label_Comment_TextEdit.setGeometry(QtCore.QRect(490, 680, 351, 51))
        self.Label_Comment_TextEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Label_Comment_TextEdit.setObjectName("Label_Comment_TextEdit")
        self.Label_Filename_ComboBox = QtWidgets.QComboBox(self.tab)
        self.Label_Filename_ComboBox.setGeometry(QtCore.QRect(0, 406, 261, 26))
        self.Label_Filename_ComboBox.setCurrentText("")
        self.Label_Filename_ComboBox.setObjectName("Label_Filename_ComboBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 480, 1421, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Ethogram_VerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Ethogram_VerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.Ethogram_VerticalLayout.setObjectName("Ethogram_VerticalLayout")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(17, 600, 1411, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Label_Start_Frame = QtWidgets.QSpinBox(self.tab)
        self.Label_Start_Frame.setGeometry(QtCore.QRect(490, 650, 101, 24))
        self.Label_Start_Frame.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Label_Start_Frame.setMaximum(100000000)
        self.Label_Start_Frame.setObjectName("Label_Start_Frame")
        self.Label_Stop_Frame = QtWidgets.QSpinBox(self.tab)
        self.Label_Stop_Frame.setGeometry(QtCore.QRect(620, 650, 101, 24))
        self.Label_Stop_Frame.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Label_Stop_Frame.setMaximum(100000000)
        self.Label_Stop_Frame.setObjectName("Label_Stop_Frame")
        self.speed_spinbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.speed_spinbox.setGeometry(QtCore.QRect(1186, 450, 51, 24))
        self.speed_spinbox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.speed_spinbox.setDecimals(1)
        self.speed_spinbox.setMinimum(0.1)
        self.speed_spinbox.setMaximum(5.0)
        self.speed_spinbox.setSingleStep(0.1)
        self.speed_spinbox.setProperty("value", 1.0)
        self.speed_spinbox.setObjectName("speed_spinbox")
        self.Main_Tab.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.Delete_Beh_Data_Button = QtWidgets.QPushButton(self.tab_4)
        self.Delete_Beh_Data_Button.setGeometry(QtCore.QRect(20, 10, 113, 32))
        self.Delete_Beh_Data_Button.setObjectName("Delete_Beh_Data_Button")
        self.Behavior_Table = QtWidgets.QTableWidget(self.tab_4)
        self.Behavior_Table.setGeometry(QtCore.QRect(0, 50, 1431, 681))
        self.Behavior_Table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Behavior_Table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Behavior_Table.setAlternatingRowColors(True)
        self.Behavior_Table.setObjectName("Behavior_Table")
        self.Behavior_Table.setColumnCount(5)
        self.Behavior_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Behavior_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Behavior_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Behavior_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Behavior_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Behavior_Table.setHorizontalHeaderItem(4, item)
        self.Behavior_Table.horizontalHeader().setDefaultSectionSize(200)
        self.Behavior_Table.horizontalHeader().setStretchLastSection(True)
        self.Beh_Export_Button = QtWidgets.QPushButton(self.tab_4)
        self.Beh_Export_Button.setGeometry(QtCore.QRect(140, 10, 113, 32))
        self.Beh_Export_Button.setObjectName("Beh_Export_Button")
        self.Main_Tab.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.Preview_Save_Button = QtWidgets.QPushButton(self.tab_3)
        self.Preview_Save_Button.setGeometry(QtCore.QRect(1250, 690, 113, 32))
        self.Preview_Save_Button.setObjectName("Preview_Save_Button")
        self.savedBehaviorEntryLabel = QtWidgets.QLabel(self.tab_3)
        self.savedBehaviorEntryLabel.setGeometry(QtCore.QRect(50, 540, 60, 16))
        self.savedBehaviorEntryLabel.setObjectName("savedBehaviorEntryLabel")
        self.saveDashLabel = QtWidgets.QLabel(self.tab_3)
        self.saveDashLabel.setGeometry(QtCore.QRect(235, 571, 16, 16))
        self.saveDashLabel.setObjectName("saveDashLabel")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(80, 20, 511, 411))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.Preview_Ant_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.Preview_Ant_Layout.setContentsMargins(0, 0, 0, 0)
        self.Preview_Ant_Layout.setObjectName("Preview_Ant_Layout")
        self.Preview_Behavior_ComboBox = QtWidgets.QComboBox(self.tab_3)
        self.Preview_Behavior_ComboBox.setGeometry(QtCore.QRect(130, 508, 221, 26))
        self.Preview_Behavior_ComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Preview_Behavior_ComboBox.setObjectName("Preview_Behavior_ComboBox")
        self.Preview_Play_Button = QtWidgets.QPushButton(self.tab_3)
        self.Preview_Play_Button.setGeometry(QtCore.QRect(670, 470, 113, 32))
        self.Preview_Play_Button.setObjectName("Preview_Play_Button")
        self.Preview_Entry_ComboBox = QtWidgets.QComboBox(self.tab_3)
        self.Preview_Entry_ComboBox.setGeometry(QtCore.QRect(130, 536, 221, 26))
        self.Preview_Entry_ComboBox.setObjectName("Preview_Entry_ComboBox")
        self.frameLabel2 = QtWidgets.QLabel(self.tab_3)
        self.frameLabel2.setGeometry(QtCore.QRect(66, 572, 41, 16))
        self.frameLabel2.setObjectName("frameLabel2")
        self.savedBehaviorLabel = QtWidgets.QLabel(self.tab_3)
        self.savedBehaviorLabel.setGeometry(QtCore.QRect(10, 510, 101, 16))
        self.savedBehaviorLabel.setObjectName("savedBehaviorLabel")
        self.Preview_Ant_ComboBox = QtWidgets.QComboBox(self.tab_3)
        self.Preview_Ant_ComboBox.setGeometry(QtCore.QRect(380, 440, 211, 26))
        self.Preview_Ant_ComboBox.setObjectName("Preview_Ant_ComboBox")
        self.Preview_Ant_ComboBox.addItem("")
        self.Preview_Ant_ComboBox.addItem("")
        self.Preview_Ant_ComboBox.addItem("")
        self.Preview_map_ComboBox = QtWidgets.QComboBox(self.tab_3)
        self.Preview_map_ComboBox.setGeometry(QtCore.QRect(1150, 440, 211, 26))
        self.Preview_map_ComboBox.setObjectName("Preview_map_ComboBox")
        self.Preview_map_ComboBox.addItem("")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(840, 20, 521, 411))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.Preview_tSNE_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.Preview_tSNE_Layout.setContentsMargins(0, 0, 0, 0)
        self.Preview_tSNE_Layout.setObjectName("Preview_tSNE_Layout")
        self.Preview_Comment_Label = QtWidgets.QLabel(self.tab_3)
        self.Preview_Comment_Label.setGeometry(QtCore.QRect(48, 598, 291, 21))
        self.Preview_Comment_Label.setObjectName("Preview_Comment_Label")
        self.Comment_Label = QtWidgets.QLabel(self.tab_3)
        self.Comment_Label.setGeometry(QtCore.QRect(133, 603, 361, 121))
        self.Comment_Label.setText("")
        self.Comment_Label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Comment_Label.setObjectName("Comment_Label")
        self.Preview_Start_Frame_LineEdit = QtWidgets.QSpinBox(self.tab_3)
        self.Preview_Start_Frame_LineEdit.setGeometry(QtCore.QRect(130, 570, 101, 24))
        self.Preview_Start_Frame_LineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Preview_Start_Frame_LineEdit.setMaximum(100000000)
        self.Preview_Start_Frame_LineEdit.setObjectName("Preview_Start_Frame_LineEdit")
        self.Preview_Stop_Frame_LineEdit = QtWidgets.QSpinBox(self.tab_3)
        self.Preview_Stop_Frame_LineEdit.setGeometry(QtCore.QRect(250, 570, 101, 24))
        self.Preview_Stop_Frame_LineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Preview_Stop_Frame_LineEdit.setMaximum(100000000)
        self.Preview_Stop_Frame_LineEdit.setObjectName("Preview_Stop_Frame_LineEdit")
        self.Main_Tab.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menutools = QtWidgets.QMenu(self.menubar)
        self.menutools.setObjectName("menutools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setEnabled(False)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionImport_Data = QtWidgets.QAction(MainWindow)
        self.actionImport_Data.setObjectName("actionImport_Data")
        self.action_tools_toggle = QtWidgets.QAction(MainWindow)
        self.action_tools_toggle.setObjectName("action_tools_toggle")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menutools.menuAction())

        self.retranslateUi(MainWindow)
        self.Main_Tab.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Behavior Mapping"))
        self.Data_Table.setSortingEnabled(True)
        item = self.Data_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Folder Key"))
        item = self.Data_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "# Frames"))
        item = self.Data_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Folder Path"))
        self.Data_Import_Button.setText(_translate("MainWindow", "Import Data..."))
        self.Delete_Data_Button.setText(_translate("MainWindow", "Delete"))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.tab_2), _translate("MainWindow", "Data"))
        self.Label_Play_Button.setToolTip(_translate("MainWindow", "opt+space", "opt+space"))
        self.Label_Play_Button.setText(_translate("MainWindow", "Play"))
        self.Label_Frame_Number_Label.setText(_translate("MainWindow", "0/0"))
        self.Label_Left_Button.setText(_translate("MainWindow", "<"))
        self.Label_Right_Button.setText(_translate("MainWindow", ">"))
        self.Label_Population_ComboBox.setItemText(0, _translate("MainWindow", "HDBSCAN Cluster"))
        self.Label_Population_ComboBox.setItemText(1, _translate("MainWindow", "Density"))
        self.Label_Individual_ComboBox.setItemText(0, _translate("MainWindow", "Points (HDBSCAN)"))
        self.Label_Ant_ComboBox.setItemText(0, _translate("MainWindow", "Skeleton"))
        self.Label_Ant_ComboBox.setItemText(1, _translate("MainWindow", "Skeleton + Video"))
        self.Label_Ant_ComboBox.setItemText(2, _translate("MainWindow", "Video"))
        self.Label_Behavior_Label.setText(_translate("MainWindow", "Behavior:"))
        self.Label_Add_Button.setText(_translate("MainWindow", "Add"))
        self.Label_Behavior_Label_2.setText(_translate("MainWindow", "Behavior:"))
        self.Label_Enter_Button.setText(_translate("MainWindow", "Enter"))
        self.dashLabel.setText(_translate("MainWindow", "-"))
        self.Label_Frame_Range_Label.setText(_translate("MainWindow", "Frame Range:"))
        self.Label_Comment_Label.setText(_translate("MainWindow", "Comment:"))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.tab), _translate("MainWindow", "Label"))
        self.Delete_Beh_Data_Button.setText(_translate("MainWindow", "Delete"))
        self.Behavior_Table.setSortingEnabled(True)
        item = self.Behavior_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Folder Key"))
        item = self.Behavior_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Behavior"))
        item = self.Behavior_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Frame Start"))
        item = self.Behavior_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Frame Stop"))
        item = self.Behavior_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Comment"))
        self.Beh_Export_Button.setText(_translate("MainWindow", "Export"))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.tab_4), _translate("MainWindow", "Behaviors"))
        self.Preview_Save_Button.setText(_translate("MainWindow", "Save"))
        self.savedBehaviorEntryLabel.setText(_translate("MainWindow", "Entry No."))
        self.saveDashLabel.setText(_translate("MainWindow", "-"))
        self.Preview_Play_Button.setText(_translate("MainWindow", "Play"))
        self.frameLabel2.setText(_translate("MainWindow", "Frame:"))
        self.savedBehaviorLabel.setText(_translate("MainWindow", "Saved Behavior"))
        self.Preview_Ant_ComboBox.setItemText(0, _translate("MainWindow", "Skeleton"))
        self.Preview_Ant_ComboBox.setItemText(1, _translate("MainWindow", "Skeleton + Video"))
        self.Preview_Ant_ComboBox.setItemText(2, _translate("MainWindow", "Video"))
        self.Preview_map_ComboBox.setItemText(0, _translate("MainWindow", "Points (HDBSCAN)"))
        self.Preview_Comment_Label.setText(_translate("MainWindow", "Comment:"))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.tab_3), _translate("MainWindow", "Preview"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menutools.setTitle(_translate("MainWindow", "tools"))
        self.actionSave.setText(_translate("MainWindow", "Save         cmd+s"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as ..."))
        self.actionImport_Data.setText(_translate("MainWindow", "Import Data"))
        self.action_tools_toggle.setText(_translate("MainWindow", "play/stop (opt+space)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
