# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 803)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Main_Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Main_Tab.setGeometry(QtCore.QRect(0, 0, 1441, 821))
        self.Main_Tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Main_Tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.Main_Tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Main_Tab.setObjectName("Main_Tab")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Data_Table = QtWidgets.QTableWidget(self.tab_2)
        self.Data_Table.setGeometry(QtCore.QRect(0, 50, 1431, 701))
        self.Data_Table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Data_Table.setObjectName("Data_Table")
        self.Data_Table.setColumnCount(3)
        self.Data_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Data_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Data_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Data_Table.setHorizontalHeaderItem(2, item)
        self.Data_Table.horizontalHeader().setDefaultSectionSize(200)
        self.Data_Table.horizontalHeader().setStretchLastSection(True)
        self.Data_Import_Button = QtWidgets.QPushButton(self.tab_2)
        self.Data_Import_Button.setGeometry(QtCore.QRect(20, 10, 113, 32))
        self.Data_Import_Button.setObjectName("Data_Import_Button")
        self.Main_Tab.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 471, 401))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.Label_Ant_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.Label_Ant_Layout.setContentsMargins(0, 0, 0, 0)
        self.Label_Ant_Layout.setObjectName("Label_Ant_Layout")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(480, 0, 471, 401))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.Label_Individual_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.Label_Individual_Layout.setContentsMargins(0, 0, 0, 0)
        self.Label_Individual_Layout.setObjectName("Label_Individual_Layout")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(960, 0, 471, 401))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.Label_Population_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.Label_Population_Layout.setContentsMargins(0, 0, 0, 0)
        self.Label_Population_Layout.setObjectName("Label_Population_Layout")
        self.Label_HSlider = QtWidgets.QSlider(self.tab)
        self.Label_HSlider.setGeometry(QtCore.QRect(70, 453, 1181, 22))
        self.Label_HSlider.setOrientation(QtCore.Qt.Horizontal)
        self.Label_HSlider.setObjectName("Label_HSlider")
        self.Label_Play_Button = QtWidgets.QPushButton(self.tab)
        self.Label_Play_Button.setGeometry(QtCore.QRect(0, 450, 71, 32))
        self.Label_Play_Button.setObjectName("Label_Play_Button")
        self.Label_Frame_Number_Label = QtWidgets.QLabel(self.tab)
        self.Label_Frame_Number_Label.setGeometry(QtCore.QRect(1300, 446, 81, 41))
        self.Label_Frame_Number_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Frame_Number_Label.setWordWrap(True)
        self.Label_Frame_Number_Label.setObjectName("Label_Frame_Number_Label")
        self.Label_Left_Button = QtWidgets.QPushButton(self.tab)
        self.Label_Left_Button.setGeometry(QtCore.QRect(1250, 450, 51, 32))
        self.Label_Left_Button.setObjectName("Label_Left_Button")
        self.Label_Right_Button = QtWidgets.QPushButton(self.tab)
        self.Label_Right_Button.setGeometry(QtCore.QRect(1380, 450, 51, 32))
        self.Label_Right_Button.setObjectName("Label_Right_Button")
        self.Label_Population_ComboBox = QtWidgets.QComboBox(self.tab)
        self.Label_Population_ComboBox.setGeometry(QtCore.QRect(1223, 407, 211, 26))
        self.Label_Population_ComboBox.setObjectName("Label_Population_ComboBox")
        self.Label_Population_ComboBox.addItem("")
        self.Label_Population_ComboBox.addItem("")
        self.Label_Individual_ComboBox = QtWidgets.QComboBox(self.tab)
        self.Label_Individual_ComboBox.setGeometry(QtCore.QRect(740, 407, 211, 26))
        self.Label_Individual_ComboBox.setObjectName("Label_Individual_ComboBox")
        self.Label_Individual_ComboBox.addItem("")
        self.Label_Ant_ComboBox = QtWidgets.QComboBox(self.tab)
        self.Label_Ant_ComboBox.setGeometry(QtCore.QRect(260, 406, 211, 26))
        self.Label_Ant_ComboBox.setObjectName("Label_Ant_ComboBox")
        self.Label_Ant_ComboBox.addItem("")
        self.Label_Ant_ComboBox.addItem("")
        self.Label_Ant_ComboBox.addItem("")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(0, 430, 1431, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Label_tSNE_Label = QtWidgets.QLabel(self.tab)
        self.Label_tSNE_Label.setGeometry(QtCore.QRect(490, 409, 221, 16))
        self.Label_tSNE_Label.setObjectName("Label_tSNE_Label")
        self.Label_Behavior_Label = QtWidgets.QLabel(self.tab)
        self.Label_Behavior_Label.setGeometry(QtCore.QRect(30, 620, 60, 16))
        self.Label_Behavior_Label.setObjectName("Label_Behavior_Label")
        self.Label_Add_Behavior_LineEdit = QtWidgets.QLineEdit(self.tab)
        self.Label_Add_Behavior_LineEdit.setGeometry(QtCore.QRect(100, 620, 171, 21))
        self.Label_Add_Behavior_LineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Label_Add_Behavior_LineEdit.setObjectName("Label_Add_Behavior_LineEdit")
        self.Label_Add_Button = QtWidgets.QPushButton(self.tab)
        self.Label_Add_Button.setGeometry(QtCore.QRect(290, 620, 101, 32))
        self.Label_Add_Button.setObjectName("Label_Add_Button")
        self.Label_Behavior_Label_2 = QtWidgets.QLabel(self.tab)
        self.Label_Behavior_Label_2.setGeometry(QtCore.QRect(50, 660, 61, 16))
        self.Label_Behavior_Label_2.setObjectName("Label_Behavior_Label_2")
        self.Label_Behavior_ComboBox = QtWidgets.QComboBox(self.tab)
        self.Label_Behavior_ComboBox.setGeometry(QtCore.QRect(140, 660, 210, 26))
        self.Label_Behavior_ComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Label_Behavior_ComboBox.setFocusPolicy(QtCore.Qt.TabFocus)
        self.Label_Behavior_ComboBox.setObjectName("Label_Behavior_ComboBox")
        self.Label_Enter_Button = QtWidgets.QPushButton(self.tab)
        self.Label_Enter_Button.setGeometry(QtCore.QRect(850, 700, 91, 32))
        self.Label_Enter_Button.setObjectName("Label_Enter_Button")
        self.dashLabel = QtWidgets.QLabel(self.tab)
        self.dashLabel.setGeometry(QtCore.QRect(250, 690, 16, 16))
        self.dashLabel.setObjectName("dashLabel")
        self.Label_Stop_Frame = QtWidgets.QLineEdit(self.tab)
        self.Label_Stop_Frame.setGeometry(QtCore.QRect(280, 690, 91, 21))
        self.Label_Stop_Frame.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Label_Stop_Frame.setText("")
        self.Label_Stop_Frame.setObjectName("Label_Stop_Frame")
        self.Label_Frame_Range_Label = QtWidgets.QLabel(self.tab)
        self.Label_Frame_Range_Label.setGeometry(QtCore.QRect(30, 690, 91, 20))
        self.Label_Frame_Range_Label.setObjectName("Label_Frame_Range_Label")
        self.Label_Start_Frame = QtWidgets.QLineEdit(self.tab)
        self.Label_Start_Frame.setGeometry(QtCore.QRect(140, 690, 91, 21))
        self.Label_Start_Frame.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Label_Start_Frame.setText("")
        self.Label_Start_Frame.setObjectName("Label_Start_Frame")
        self.Label_Comment_Label = QtWidgets.QLabel(self.tab)
        self.Label_Comment_Label.setGeometry(QtCore.QRect(400, 620, 61, 20))
        self.Label_Comment_Label.setObjectName("Label_Comment_Label")
        self.Label_Comment_TextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.Label_Comment_TextEdit.setGeometry(QtCore.QRect(490, 620, 351, 111))
        self.Label_Comment_TextEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Label_Comment_TextEdit.setObjectName("Label_Comment_TextEdit")
        self.Label_Filename_ComboBox = QtWidgets.QComboBox(self.tab)
        self.Label_Filename_ComboBox.setGeometry(QtCore.QRect(0, 406, 261, 26))
        self.Label_Filename_ComboBox.setCurrentText("")
        self.Label_Filename_ComboBox.setObjectName("Label_Filename_ComboBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 480, 1421, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Ethogram_VerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Ethogram_VerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.Ethogram_VerticalLayout.setObjectName("Ethogram_VerticalLayout")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(17, 600, 1411, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Main_Tab.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.Behavior_Table = QtWidgets.QTableWidget(self.tab_4)
        self.Behavior_Table.setGeometry(QtCore.QRect(0, 40, 1431, 711))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Behavior_Table.sizePolicy().hasHeightForWidth())
        self.Behavior_Table.setSizePolicy(sizePolicy)
        self.Behavior_Table.setMinimumSize(QtCore.QSize(1431, 0))
        self.Behavior_Table.setMaximumSize(QtCore.QSize(1431, 16777215))
        self.Behavior_Table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Behavior_Table.setAutoFillBackground(False)
        self.Behavior_Table.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Behavior_Table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Behavior_Table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Behavior_Table.setGridStyle(QtCore.Qt.CustomDashLine)
        self.Behavior_Table.setObjectName("Behavior_Table")
        self.Behavior_Table.setColumnCount(7)
        self.Behavior_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Behavior_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Behavior_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Behavior_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Behavior_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Behavior_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Behavior_Table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Behavior_Table.setHorizontalHeaderItem(6, item)
        self.Behavior_Table.horizontalHeader().setDefaultSectionSize(150)
        self.Behavior_Table.horizontalHeader().setMinimumSectionSize(30)
        self.Behavior_Table.horizontalHeader().setSortIndicatorShown(False)
        self.Behavior_Table.horizontalHeader().setStretchLastSection(True)
        self.Behavior_Table.verticalHeader().setVisible(False)
        self.Behavior_Table.verticalHeader().setStretchLastSection(False)
        self.Main_Tab.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.Preview_Save_Button = QtWidgets.QPushButton(self.tab_3)
        self.Preview_Save_Button.setGeometry(QtCore.QRect(1250, 690, 113, 32))
        self.Preview_Save_Button.setObjectName("Preview_Save_Button")
        self.Preview_Update_Button = QtWidgets.QPushButton(self.tab_3)
        self.Preview_Update_Button.setGeometry(QtCore.QRect(410, 570, 131, 32))
        self.Preview_Update_Button.setObjectName("Preview_Update_Button")
        self.savedBehaviorEntryLabel = QtWidgets.QLabel(self.tab_3)
        self.savedBehaviorEntryLabel.setGeometry(QtCore.QRect(60, 540, 60, 16))
        self.savedBehaviorEntryLabel.setObjectName("savedBehaviorEntryLabel")
        self.saveDashLabel = QtWidgets.QLabel(self.tab_3)
        self.saveDashLabel.setGeometry(QtCore.QRect(230, 570, 16, 16))
        self.saveDashLabel.setObjectName("saveDashLabel")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(90, 20, 491, 411))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.Preview_Ant_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.Preview_Ant_Layout.setContentsMargins(0, 0, 0, 0)
        self.Preview_Ant_Layout.setObjectName("Preview_Ant_Layout")
        self.Preview_Stop_Frame_LineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.Preview_Stop_Frame_LineEdit.setGeometry(QtCore.QRect(250, 570, 91, 21))
        self.Preview_Stop_Frame_LineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Preview_Stop_Frame_LineEdit.setText("")
        self.Preview_Stop_Frame_LineEdit.setObjectName("Preview_Stop_Frame_LineEdit")
        self.saveFilenameLabel = QtWidgets.QLabel(self.tab_3)
        self.saveFilenameLabel.setGeometry(QtCore.QRect(920, 630, 131, 16))
        self.saveFilenameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.saveFilenameLabel.setObjectName("saveFilenameLabel")
        self.Preview_Behavior_ComboBox = QtWidgets.QComboBox(self.tab_3)
        self.Preview_Behavior_ComboBox.setGeometry(QtCore.QRect(130, 500, 211, 26))
        self.Preview_Behavior_ComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Preview_Behavior_ComboBox.setObjectName("Preview_Behavior_ComboBox")
        self.Preview_Play_Button = QtWidgets.QPushButton(self.tab_3)
        self.Preview_Play_Button.setGeometry(QtCore.QRect(670, 470, 113, 32))
        self.Preview_Play_Button.setObjectName("Preview_Play_Button")
        self.Preview_Filename_LineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.Preview_Filename_LineEdit.setGeometry(QtCore.QRect(1100, 630, 241, 21))
        self.Preview_Filename_LineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Preview_Filename_LineEdit.setObjectName("Preview_Filename_LineEdit")
        self.Preview_Entry_ComboBox = QtWidgets.QComboBox(self.tab_3)
        self.Preview_Entry_ComboBox.setGeometry(QtCore.QRect(130, 540, 211, 26))
        self.Preview_Entry_ComboBox.setObjectName("Preview_Entry_ComboBox")
        self.Preview_tSNEY_Label = QtWidgets.QLabel(self.tab_3)
        self.Preview_tSNEY_Label.setGeometry(QtCore.QRect(30, 640, 241, 16))
        self.Preview_tSNEY_Label.setObjectName("Preview_tSNEY_Label")
        self.Preview_tSNEX_Label = QtWidgets.QLabel(self.tab_3)
        self.Preview_tSNEX_Label.setGeometry(QtCore.QRect(30, 620, 241, 16))
        self.Preview_tSNEX_Label.setObjectName("Preview_tSNEX_Label")
        self.frameLabel2 = QtWidgets.QLabel(self.tab_3)
        self.frameLabel2.setGeometry(QtCore.QRect(67, 574, 41, 16))
        self.frameLabel2.setObjectName("frameLabel2")
        self.savedBehaviorLabel = QtWidgets.QLabel(self.tab_3)
        self.savedBehaviorLabel.setGeometry(QtCore.QRect(20, 510, 101, 16))
        self.savedBehaviorLabel.setObjectName("savedBehaviorLabel")
        self.Preview_Ant_ComboBox = QtWidgets.QComboBox(self.tab_3)
        self.Preview_Ant_ComboBox.setGeometry(QtCore.QRect(370, 440, 211, 26))
        self.Preview_Ant_ComboBox.setObjectName("Preview_Ant_ComboBox")
        self.Preview_Ant_ComboBox.addItem("")
        self.Preview_Ant_ComboBox.addItem("")
        self.Preview_Ant_ComboBox.addItem("")
        self.Preview_tSNE_ComboBox = QtWidgets.QComboBox(self.tab_3)
        self.Preview_tSNE_ComboBox.setGeometry(QtCore.QRect(1120, 440, 211, 26))
        self.Preview_tSNE_ComboBox.setObjectName("Preview_tSNE_ComboBox")
        self.Preview_tSNE_ComboBox.addItem("")
        self.Preview_tSNE_ComboBox.addItem("")
        self.Preview_tSNE_ComboBox.addItem("")
        self.Preview_tSNE_ComboBox.addItem("")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(840, 20, 491, 411))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.Preview_tSNE_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.Preview_tSNE_Layout.setContentsMargins(0, 0, 0, 0)
        self.Preview_tSNE_Layout.setObjectName("Preview_tSNE_Layout")
        self.editBehaviorLabel_4 = QtWidgets.QLabel(self.tab_3)
        self.editBehaviorLabel_4.setGeometry(QtCore.QRect(840, 440, 221, 16))
        self.editBehaviorLabel_4.setObjectName("editBehaviorLabel_4")
        self.Preview_Start_Frame_LineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.Preview_Start_Frame_LineEdit.setGeometry(QtCore.QRect(130, 570, 91, 21))
        self.Preview_Start_Frame_LineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Preview_Start_Frame_LineEdit.setText("")
        self.Preview_Start_Frame_LineEdit.setObjectName("Preview_Start_Frame_LineEdit")
        self.Preview_Comment_Label = QtWidgets.QLabel(self.tab_3)
        self.Preview_Comment_Label.setGeometry(QtCore.QRect(30, 660, 241, 16))
        self.Preview_Comment_Label.setObjectName("Preview_Comment_Label")
        self.Preview_Ant_Save_ComboBox = QtWidgets.QComboBox(self.tab_3)
        self.Preview_Ant_Save_ComboBox.setGeometry(QtCore.QRect(1130, 540, 211, 26))
        self.Preview_Ant_Save_ComboBox.setObjectName("Preview_Ant_Save_ComboBox")
        self.Preview_Ant_Save_ComboBox.addItem("")
        self.Preview_Ant_Save_ComboBox.addItem("")
        self.Preview_Ant_Save_ComboBox.addItem("")
        self.Preview_tSNE_Save_ComboBox = QtWidgets.QComboBox(self.tab_3)
        self.Preview_tSNE_Save_ComboBox.setGeometry(QtCore.QRect(1130, 570, 211, 26))
        self.Preview_tSNE_Save_ComboBox.setObjectName("Preview_tSNE_Save_ComboBox")
        self.Preview_tSNE_Save_ComboBox.addItem("")
        self.Preview_tSNE_Save_ComboBox.addItem("")
        self.Preview_tSNE_Save_ComboBox.addItem("")
        self.Preview_tSNE_Save_ComboBox.addItem("")
        self.saveFilenameLabel_2 = QtWidgets.QLabel(self.tab_3)
        self.saveFilenameLabel_2.setGeometry(QtCore.QRect(870, 540, 231, 16))
        self.saveFilenameLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.saveFilenameLabel_2.setObjectName("saveFilenameLabel_2")
        self.saveFilenameLabel_3 = QtWidgets.QLabel(self.tab_3)
        self.saveFilenameLabel_3.setGeometry(QtCore.QRect(870, 560, 231, 16))
        self.saveFilenameLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.saveFilenameLabel_3.setObjectName("saveFilenameLabel_3")
        self.Main_Tab.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionImport_Data = QtWidgets.QAction(MainWindow)
        self.actionImport_Data.setObjectName("actionImport_Data")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionImport_Data)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.Main_Tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Behavior Mapping"))
        item = self.Data_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Folder Key"))
        item = self.Data_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "# Frames"))
        item = self.Data_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Folder Path"))
        self.Data_Import_Button.setText(_translate("MainWindow", "Import Data..."))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.tab_2), _translate("MainWindow", "Data"))
        self.Label_Play_Button.setText(_translate("MainWindow", "Play"))
        self.Label_Frame_Number_Label.setText(_translate("MainWindow", "0/0"))
        self.Label_Left_Button.setText(_translate("MainWindow", "<"))
        self.Label_Right_Button.setText(_translate("MainWindow", ">"))
        self.Label_Population_ComboBox.setItemText(0, _translate("MainWindow", "HDBSCAN Cluster"))
        self.Label_Population_ComboBox.setItemText(1, _translate("MainWindow", "Density"))
        self.Label_Individual_ComboBox.setItemText(0, _translate("MainWindow", "Points (HDBSCAN)"))
        self.Label_Ant_ComboBox.setItemText(0, _translate("MainWindow", "Skeleton"))
        self.Label_Ant_ComboBox.setItemText(1, _translate("MainWindow", "Skeleton + Video"))
        self.Label_Ant_ComboBox.setItemText(2, _translate("MainWindow", "Video"))
        self.Label_tSNE_Label.setText(_translate("MainWindow", "tSNE: (0,0)"))
        self.Label_Behavior_Label.setText(_translate("MainWindow", "Behavior:"))
        self.Label_Add_Button.setText(_translate("MainWindow", "Add"))
        self.Label_Behavior_Label_2.setText(_translate("MainWindow", "Behavior:"))
        self.Label_Enter_Button.setText(_translate("MainWindow", "Enter"))
        self.dashLabel.setText(_translate("MainWindow", "-"))
        self.Label_Frame_Range_Label.setText(_translate("MainWindow", "Frame Range:"))
        self.Label_Comment_Label.setText(_translate("MainWindow", "Comment:"))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.tab), _translate("MainWindow", "Label"))
        self.Behavior_Table.setSortingEnabled(False)
        item = self.Behavior_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Folder Key"))
        item = self.Behavior_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Behavior"))
        item = self.Behavior_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Frame Start"))
        item = self.Behavior_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Frame Stop"))
        item = self.Behavior_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "tSNE X (mean)"))
        item = self.Behavior_Table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "tSNE Y (mean)"))
        item = self.Behavior_Table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Comment"))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.tab_4), _translate("MainWindow", "Behaviors"))
        self.Preview_Save_Button.setText(_translate("MainWindow", "Save"))
        self.Preview_Update_Button.setText(_translate("MainWindow", "Update"))
        self.savedBehaviorEntryLabel.setText(_translate("MainWindow", "Entry No."))
        self.saveDashLabel.setText(_translate("MainWindow", "-"))
        self.saveFilenameLabel.setText(_translate("MainWindow", "Filename"))
        self.Preview_Play_Button.setText(_translate("MainWindow", "Play"))
        self.Preview_tSNEY_Label.setText(_translate("MainWindow", "tSNE Y (mean): NaN"))
        self.Preview_tSNEX_Label.setText(_translate("MainWindow", "tSNE X (mean): NaN"))
        self.frameLabel2.setText(_translate("MainWindow", "Frame:"))
        self.savedBehaviorLabel.setText(_translate("MainWindow", "Saved Behavior"))
        self.Preview_Ant_ComboBox.setItemText(0, _translate("MainWindow", "Skeleton"))
        self.Preview_Ant_ComboBox.setItemText(1, _translate("MainWindow", "Skeleton + Video"))
        self.Preview_Ant_ComboBox.setItemText(2, _translate("MainWindow", "Video"))
        self.Preview_tSNE_ComboBox.setItemText(0, _translate("MainWindow", "Points"))
        self.Preview_tSNE_ComboBox.setItemText(1, _translate("MainWindow", "Points + Density"))
        self.Preview_tSNE_ComboBox.setItemText(2, _translate("MainWindow", "Points + Watershed"))
        self.Preview_tSNE_ComboBox.setItemText(3, _translate("MainWindow", "Points + Density + Watershed"))
        self.editBehaviorLabel_4.setText(_translate("MainWindow", "tSNE: (0,0)"))
        self.Preview_Comment_Label.setText(_translate("MainWindow", "Comment:"))
        self.Preview_Ant_Save_ComboBox.setItemText(0, _translate("MainWindow", "Skeleton"))
        self.Preview_Ant_Save_ComboBox.setItemText(1, _translate("MainWindow", "Skeleton + Video"))
        self.Preview_Ant_Save_ComboBox.setItemText(2, _translate("MainWindow", "Video"))
        self.Preview_tSNE_Save_ComboBox.setItemText(0, _translate("MainWindow", "Points"))
        self.Preview_tSNE_Save_ComboBox.setItemText(1, _translate("MainWindow", "Points + Density"))
        self.Preview_tSNE_Save_ComboBox.setItemText(2, _translate("MainWindow", "Points + Watershed"))
        self.Preview_tSNE_Save_ComboBox.setItemText(3, _translate("MainWindow", "Points + Density + Watershed"))
        self.saveFilenameLabel_2.setText(_translate("MainWindow", "Ant Video:"))
        self.saveFilenameLabel_3.setText(_translate("MainWindow", "tSNE Plot:"))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.tab_3), _translate("MainWindow", "Preview"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as ..."))
        self.actionImport_Data.setText(_translate("MainWindow", "Import Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
